name: golang-ci

on:
  push:
    paths:
      - "**.go"
      - ./.github/workflows/golangci.yml

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: check out code into Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: './...'